# Generated by Django 4.0.4 on 2022-05-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('login', '0002_user_has_confirmed_confirmstring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
